### PR TITLE
Adding snippet to log SessionInfo from WebhookRequest

### PR DESCRIPTION
**Pull request by hjosiah**
- https://github.com/googleapis/python-dialogflow-cx/issues/444
- [ Done] Ensure the tests and linter pass
- [ Done] Code coverage does not decrease (if any source code was changed)
- [N/A ] Appropriate docs were updated (if necessary)

Fixes #<444> 🦕

### CODE REVIEW

**Review by nicain — CHANGES_REQUESTED** [review]
Can you please factor the "session components" and "build session uris" into a fixture, and then make two separate test functions (One for "session without environment path" and one for "session with environment path")?

**Comment by hjosiah** [comment]
I made the changes, hopefully not an overkill when it comes to using fixtures. I also did a `git commit --amend --no-edit` and rebase so my commit message seems to have failed a check

**Review by nicain — APPROVED** [review]
LGTM

**Comment by hjosiah** [comment]
Switching to https://github.com/googleapis/python-dialogflow-cx/pull/457

**Pull request closed without merging**
